[[edge_functions]]
  function = "generate-sermon"
  path = "/api/generate-sermon"

# Functions configuration
[functions]
  directory = "netlify/functions"

# Include markdown files for the unified function
[functions."markdown-content"]
  included_files = ["netlify/functions/markdown-files/**"]

# Include audio files for the markdown-assets function
[functions."markdown-assets"]
  included_files = ["netlify/functions/markdown-assets/**"]

# Redirect API routes to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 