[[edge_functions]]
  function = "generate-sermon"
  path = "/api/generate-sermon"

# Functions configuration
[functions]
  directory = "netlify/functions"

# Ensure markdown files are included with the markdown-files function
[functions."markdown-files"]
  included_files = ["netlify/functions/markdown-files/markdown/**"]

# Ensure markdown files are included with the markdown-content function
[functions."markdown-content"]
  included_files = ["netlify/functions/markdown-content/markdown/**"]

# Redirect API routes to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 