// Emoji mapping for common emojis
const emojiMap: Record<string, string> = {
  smile: '😊',
  heart: '❤️',
  thumbsup: '👍',
  thumbsdown: '👎',
  fire: '🔥',
  star: '⭐',
  check: '✅',
  cross: '❌',
  warning: '⚠️',
  info: 'ℹ️',
  question: '❓',
  exclamation: '❗',
  pray: '🙏',
  bible: '📖',
  church: '⛪',
  cross_symbol: '✝️',
  dove: '🕊️',
  light: '💡',
  love: '💕',
  peace: '☮️',
  hope: '🌟',
  faith: '✨',
  joy: '😄',
  praise: '🙌',
  worship: '🛐',
  blessed: '😇',
  angel: '👼',
  crown: '👑',
  book: '📚',
  scroll: '📜',
  candle: '🕯️',
  flame: '🔥',
  shepherd: '🐑',
  fish: '🐟',
  bread: '🍞',
  wine: '🍷',
  rainbow: '🌈',
  mountain: '⛰️',
  sun: '☀️',
  moon: '🌙',
  wave: '👋',
  hands: '🤲',
  handshake: '🤝',
  hug: '🤗',
  clap: '👏',
  muscle: '💪',
  ear: '👂',
  eye: '👁️',
  lips: '👄',
  footsteps: '👣',
  path: '🛤️',
  door: '🚪',
  key: '🗝️',
  gift: '🎁',
  tree: '🌳',
  flower: '🌸',
  rose: '🌹',
  tulip: '🌷',
  seed: '🌱',
  fruit: '🍇',
  water: '💧',
  rock: '🪨',
  diamond: '💎',
  gold: '🥇',
  silver: '🥈',
  bronze: '🥉',
  trophy: '🏆',
  medal: '🏅',
  flag: '🏳️',
  home: '🏠',
  family: '👨‍👩‍👧‍👦',
  baby: '👶',
  child: '🧒',
  man: '👨',
  woman: '👩',
  elderly: '👴',
  teacher: '👨‍🏫',
  student: '🧑‍🎓',
  music: '🎵',
  note: '🎶',
  trumpet: '🎺',
  drum: '🥁',
  guitar: '🎸',
  piano: '🎹',
  bell: '🔔',
  earth: '🌍',
  globe: '🌎',
  world: '🗺️',
  compass: '🧭',
  anchor: '⚓',
  ship: '🚢',
  airplane: '✈️',
  rocket: '🚀',
  calendar: '📅',
  clock: '🕒',
  hourglass: '⏳',
  timer: '⏰',
  watch: '⌚',
  phone: '📞',
  email: '📧',
  letter: '✉️',
  pencil: '✏️',
  pen: '🖊️',
  paper: '📄',
  notebook: '📓',
  bookmark: '🔖',
  magnifying: '🔍',
  telescope: '🔭',
  microscope: '🔬',
  bulb: '💡',
  battery: '🔋',
  plug: '🔌',
  gear: '⚙️',
  hammer: '🔨',
  wrench: '🔧',
  shield: '🛡️',
  sword: '⚔️',
  bow: '🏹',
  target: '🎯',
  scales: '⚖️',
  gavel: '⚖️',
}

// Emoji extension for marked
export const emojiExtension = {
  name: 'emoji',
  level: 'inline' as const,
  start(src: string) {
    return src.indexOf(':')
  },
  tokenizer(src: string) {
    const rule = /^:(\w+):/
    const match = rule.exec(src)
    if (match) {
      const emojiName = match[1]
      const emojiChar = emojiMap[emojiName]
      if (emojiChar) {
        return {
          type: 'emoji',
          raw: match[0],
          emoji: emojiName,
          char: emojiChar,
        }
      }
    }
  },
  renderer(token: any) {
    return `<span class="emoji" title=":${token.emoji}:">${token.char}</span>`
  },
}
